server:
  port: 8080
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/mydb?characterEncoding=UTF-8
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
  application:
      name: cloud-user8080
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}